// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"golang-di/repository"
	"golang-di/service"
)

// Injectors from injector.go:

func InitializedService() *service.SimpleService {
	simpleRepository := repository.NewSimpleRepository()
	simpleService := service.NewSimpleService(simpleRepository)
	return simpleService
}
